import { z } from 'zod';

const SCRIPT_INJECTION_REGEX = /<[^>]*>|javascript:|on\w+\s*=|\$where|\$expr/i;
const SPECIAL_CHARS_STRICT_REGEX = /[<>{}()\[\]\\\/]/;

const safeString = (maxLen = 200, minLen = 0, minMsg = '') => {
  let schema = z.string().trim().max(maxLen, `Must be ${maxLen} characters or fewer`);
  if (minLen > 0) {
    schema = schema.min(minLen, minMsg || `Must be at least ${minLen} characters`);
  }
  return schema.refine((v) => !SCRIPT_INJECTION_REGEX.test(v), {
    message: 'Input contains disallowed characters.',
  });
};

const nameField = (label = 'Name') =>
  z
    .string()
    .trim()
    .min(2, `${label} must be at least 2 characters`)
    .max(100, `${label} must be 100 characters or fewer`)
    .refine((v) => !SCRIPT_INJECTION_REGEX.test(v), {
      message: 'Input contains disallowed characters.',
    })
    .refine((v) => !SPECIAL_CHARS_STRICT_REGEX.test(v), {
      message: `${label} must not contain special characters.`,
    });

const phoneField = z
  .string().trim()
  .regex(/^(\+92|0)?[3][0-9]{9}$/, 'Enter a valid Pakistani mobile number (e.g. 03001234567)')
  .max(15);

/**
 * HM Enroll Student Form Schema
 * GR No and Global Student ID are NEVER part of this form.
 * - NEW_ADMISSION: GR is auto-generated by backend, shown as readonly preview
 * - EXISTING_ENTRY: HM provides original GR from school paper records
 */
export const enrollStudentFormSchema = z
  .object({
    admissionType: z.enum(['NEW_ADMISSION', 'EXISTING_ENTRY'], {
      errorMap: () => ({ message: 'Please select admission type.' }),
    }),

    fullName: nameField('Full Name'),
    dateOfBirth: z.string().trim().optional(),
    gender: z.enum(['MALE', 'FEMALE', 'OTHER']).optional(),

    guardianName: nameField('Father/Guardian Name'),
    guardianContact: phoneField,
    residentialAddress: safeString(300).optional(),

    classId: z.string().min(1, 'Class is required'),
    sectionId: z.string().min(1, 'Section is required'),
    admissionDate: z.string().trim().optional(),

    // Only required for EXISTING_ENTRY
    manualGrNumber: z.coerce.number().int().positive().optional(),
  })
  .refine(
    (data) => {
      if (data.admissionType === 'EXISTING_ENTRY') {
        return !!data.manualGrNumber && data.manualGrNumber > 0;
      }
      return true;
    },
    {
      message: 'Please enter the original GR number from school records.',
      path: ['manualGrNumber'],
    }
  );

/**
 * Set School Code form — authorized roles only
 * The school code becomes the prefix for all Global Student IDs
 */
export const setSchoolCodeFormSchema = z.object({
  schoolCode: z
    .string().trim().toUpperCase()
    .min(2, 'School code must be at least 2 characters')
    .max(10, 'School code must not exceed 10 characters')
    .regex(/^[A-Z0-9]+$/, 'Only uppercase letters and numbers allowed (e.g. MMHA)'),
});
